#!/bin/bash

# Author: drpawpaw - 201?

# Copies a local file readable by you to the same file path location (modulo
# $HOME) on one or more remote hosts, retaining its timestamps and rwx props on
# the remote hosts. Assumes that each remote-host user has write permissions to
# the remote-host dir to which the file will be written. The copy will only
# fail on the hosts for which this is not true (assuming ssh login success).
# In the typical use case of this script permissions failures are VERY rare.

if [ ! -f "$1" ] || [ ! -r "$1" ]
then
    echo -e "\n'$1': Arg 1 must be a path to a readable file"
    exit 1
fi
file="$1"

shift 1
if [ -z "$1" ]
then
    echo -e "\nArgs 2+ are nicknames of ssh hosts to copy arg 1 to"
    exit 1
fi

for h in $@
do
    echo -e "\n$ scp -p $file $h:$file"
    scp -p -o IdentitiesOnly=true "$file" \
                           "$h":$( echo "${file}" | sed -r "s|^$HOME/||" )
done

