#!/bin/bash

# © 2020 drpawpaw - All Rights Reserved.
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version. This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more
# details: http://www.gnu.org/licenses/

# TODO: Add optional SSH server host/IP argument.

# TODO: Add optional setting of ssh server's port.

if [ 0 != $(id -u) ] || [ -z "$SUDO_USER" ]
then
    echo -e "\n${0##*/} only runs as sudo root.\n"
    exit 1
fi


function cleanUp
{
    rm -f "$TF"
    iptbls-hole -a c -d o -p t -P 22
}


userHome=$( cat /etc/passwd | grep -E "^$SUDO_USER:" | cut -d : -f6 )
TF=$( sudo -u $SUDO_USER mktemp )
echo ". $userHome/.bashrc"                              > "$TF"
echo "PS1='\n$SUDO_USER ${0##*/} \$( pwd )\nssh:22> '" >> "$TF"
echo "echo -e '\033]2;'ssh:22 ${0##*/}'\007'"          >> "$TF"
echo "cd $PWD"                                         >> "$TF"
echo "env | grep SSH"                                  >> "$TF"

# Do NOT launch iptbls-hole as sudo, because if done AND this script is
# also launched as sudo, then SUDO_USER within iptbls-hole is root!
# It's unlikely anyone would ever want SUDO_USER=root.

if ! iptbls-hole -a o -d o -p t -P 22
then
    echo -e "\niptbls-hole open hole call failed"
    cleanUp
    exit 1
fi

trap 'iptbls-hole -a c -d o -p t -P 22' \
                          SIGHUP SIGINT SIGQUIT SIGILL SIGABRT SIGFPE SIGTERM
                         #  1      2       3      4       6      8      15

sudo --login -u $SUDO_USER ssh-agent bash --rcfile "$TF"

cleanUp

